In [11]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import matplotlib as mpl
from mpl_toolkits.mplot3d import Axes3D
from random import randint

In [12]:
datos = pd.read_csv("datos_p_1.csv", header=None)

/Users/Prueba/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (4,13,22) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


(array([ 0.00343865,  0.00343775,  0.00343686, ...,  0.00382947,
         0.00382841,  0.00382737]),
 array([ 0.00379561,  0.00379806,  0.00380052, ...,  0.00023921,
         0.00024095,  0.00024273]),
 array([ -1.57195500e-04,  -1.57177400e-04,  -1.57159300e-04, ...,
         -5.15995600e-05,  -5.15956300e-05,  -5.15876400e-05]))

In [14]:
def index(p,dat):
    return 3*p + dat
colors = []
for i in range(10):
    colors.append('#%06X' % randint(0, 0xFFFFFF))

In [23]:
fig = plt.figure()
for p in range(10):
    ax = fig.gca(projection='3d')
    x = datos.iloc[:,index(p,0)]
    y = datos.iloc[:,index(p,1)]
    z = datos.iloc[:,index(p,2)]
    print(x,y,z)

0         0.003439
1         0.003438
2         0.003437
3         0.003436
4         0.003435
5         0.003434
6         0.003433
7         0.003432
8         0.003431
9         0.003431
10        0.003430
11        0.003429
12        0.003428
13        0.003427
14        0.003426
15        0.003425
16        0.003424
17        0.003423
18        0.003422
19        0.003421
20        0.003421
21        0.003420
22        0.003419
23        0.003418
24        0.003417
25        0.003416
26        0.003415
27        0.003414
28        0.003413
29        0.003412
            ...   
249970    0.003857
249971    0.003856
249972    0.003855
249973    0.003854
249974    0.003853
249975    0.003852
249976    0.003851
249977    0.003850
249978    0.003849
249979    0.003848
249980    0.003847
249981    0.003846
249982    0.003845
249983    0.003844
249984    0.003843
249985    0.003842
249986    0.003841
249987    0.003840
249988    0.003839
249989    0.003838
249990    0.003837
249991    0.

In [44]:
x,y,z = datos.iloc[:,0].values,datos.iloc[:,10].values, datos.iloc[:,20].values

In [52]:
x1,y1,z1 = datos.iloc[:,2].values,datos.iloc[:,12].values, datos.iloc[:,22].values

In [53]:
mpl.rcParams['legend.fontsize'] = 10
fig = plt.figure()
ax = fig.gca(projection='3d')
ax.plot(x, y, z, linewidth=0.6, label='sol', color='darkslateblue')
ax.plot(x1, y1, z1, linewidth=0.6, label='tierra', color='b')
ax.legend()
plt.show()

ValueError: third arg must be a format string